### ISSUE TITLE
TSP_20 task reward function

### ISSUE THREAD

**Issue by gregkocher** [pemami4911/neural-combinatorial-rl-pytorch#10]
Hi, thanks for sharing your code. 

In the file "tsp_task.py", I see the TSP reward defined in the usual way as the sum of distances between consecutive vertices in the cylce. But it looks like you also started to generalize this, or maybe had to manually tune things a bit for tsp_20? I see this:

    # For TSP_20 - map to a number between 0 and 1
    # min_len = 3.5
    # max_len = 10.
    # TODO: generalize this for any TSP size
    #tour_len = -0.1538*tour_len + 1.538 
    #tour_len[tour_len < 0.] = 0.
    return tour_len

So for the results you showed for the tsp_20 and tsp_50 tasks, did you use the usual sum of distances that would run as is in the current uncommented code, or did you find it helped to do those affine then clip operations you have commented out? Are these values derived theoretically or empirically?

Any other thoughts here in terms of generalizing the reward to work with arbitrary tour length?

Thanks!

**Comment by pemami4911** [comment]
I used the usual sum of distances for the results. I don't think that the commented out lines worked better, but it's been a while, sorry.
