### ISSUE TITLE
Meet lots of Deprecated warning with higher version of Pytorch. Do you have any idea?

### ISSUE THREAD

**Issue by caidwang** [pemami4911/neural-combinatorial-rl-pytorch#15]
Hi, thank you for your repo!  It's an awesome implement and helps me a lot. However when running it with higher version of pytorch, it raises lots of deprecated warning as this:

```
IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
```

I searched around the project but find `uint8` nowhere. Do you have any idea how to fix this? Or do I have to run it at version of 0.4. (I use 1.2 currently since the API didn't change a lot since 0.4)

**Comment by pemami4911** [comment]
I would run it with version 0.4 if at all possible. Unfortunately I wrote this code a while ago and haven't had time to update it to keep up with changes in PyTorch
