### ISSUE TITLE
variable length inputs

### ISSUE THREAD

**Issue by gregkocher** [pemami4911/neural-combinatorial-rl-pytorch#9]
Hi, thanks a lot for your code. Haven't had a chance to look through it in detail yet but it seems like a pretty solid implementation. A question though: in your to do, I see an item:

"Add support for variable length inputs"

Just wanted to clarify what this means since in general a pointer net could deal with arbitrary size inputs, so what inputs is it referring to which apparently have a fixed length?

Thanks!

**Comment by pemami4911** [comment]
What I mean by variable length inputs is just support for sequences of different length within a single minibatch. Right now, the code only supports minibatches containing sequences of equal length.
